server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel
    username: admin
    password: 1
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: phanvanthi315.1@gmail.com
    password: ubwawlbchisuixdj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    fromName: "Khách sạn 315"
    booking:
      subject: "Kết quả duyệt đơn đặt phòng"

jwt:
  signerKey: "bj0hKxleZxWk8mHcrceJBce84L5qniIsLM3UcEw6NZWiyTXXN3zTVFoBRB0BScPz"
  validDuration: 9999
  refreshableDuration: 9999

firebase:
  bucket: "hotel-booking-73711.appspot.com"
  userPath: "user/"
  roomPath: "room/"
  hotelPath: "hotel/"

frontend:
  url: "http://localhost:3000"

