server:
  port: 8080
  servlet:
    context-path: /api/hotel

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel
    username: admin
    password: 1
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true

jwt:
  signerKey: "bj0hKxleZxWk8mHcrceJBce84L5qniIsLM3UcEw6NZWiyTXXN3zTVFoBRB0BScPz"
  validDuration: 9999
  refreshableDuration: 9999

